const BREVO_API_KEY    = process.env.BREVO_API_KEY!;
const SENDER_EMAIL     = process.env.BREVO_SENDER_EMAIL!;
const SENDER_NAME      = process.env.BREVO_SENDER_NAME!;
const APP_URL          = process.env.NEXT_PUBLIC_APP_URL!;

interface SendOptions {
  to: string;
  toName?: string;
  subject: string;
  html: string;
}

export async function sendEmail({ to, toName, subject, html }: SendOptions) {
  const res = await fetch('https://api.brevo.com/v3/smtp/email', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'api-key': BREVO_API_KEY,
    },
    body: JSON.stringify({
      sender: { name: SENDER_NAME, email: SENDER_EMAIL },
      to: [{ email: to, name: toName || to }],
      subject,
      htmlContent: html,
    }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error((err as any).message || `Brevo error ${res.status}`);
  }
}

export function verificationEmail(name: string, token: string) {
  const link = `${APP_URL}/auth/callback?token=${token}`;
  return {
    subject: 'Verify your email — Warehouse Manager',
    html: `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:40px 16px;">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="max-width:560px;width:100%;">
        <tr>
          <td style="background:linear-gradient(135deg,#1d4ed8,#2563eb);border-radius:16px 16px 0 0;padding:36px 40px;text-align:center;">
            <div style="font-size:32px;margin-bottom:8px;">📦</div>
            <h1 style="margin:0;color:#fff;font-size:22px;font-weight:700;">Warehouse Manager</h1>
            <p style="margin:8px 0 0;color:#93c5fd;font-size:14px;">Verify your email address</p>
          </td>
        </tr>
        <tr>
          <td style="background:#fff;padding:36px 40px;text-align:center;">
            <p style="margin:0 0 8px;font-size:16px;color:#1e293b;">Hi <strong>${name}</strong>,</p>
            <p style="margin:0 0 28px;font-size:14px;color:#64748b;line-height:1.6;">
              Click the button below to verify your email and activate your account.
              This link expires in <strong>24 hours</strong>.
            </p>
            <a href="${link}" style="display:inline-block;background:linear-gradient(135deg,#2563eb,#7c3aed);color:#fff;font-size:15px;font-weight:600;text-decoration:none;padding:14px 36px;border-radius:12px;">
              Verify Email
            </a>
            <p style="margin:24px 0 0;font-size:12px;color:#94a3b8;">
              Or copy this link:<br>
              <span style="color:#2563eb;word-break:break-all;">${link}</span>
            </p>
          </td>
        </tr>
        <tr>
          <td style="background:#1e293b;border-radius:0 0 16px 16px;padding:20px 40px;text-align:center;">
            <p style="margin:0;font-size:12px;color:#64748b;">
              Generated by <strong style="color:#93c5fd;">Warehouse Manager</strong> · Powered by PixelCore
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`,
  };
}

export function passwordResetEmail(name: string, token: string) {
  const link = `${APP_URL}/reset-password?token=${token}`;
  return {
    subject: 'Reset your password — Warehouse Manager',
    html: `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:40px 16px;">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="max-width:560px;width:100%;">
        <tr>
          <td style="background:linear-gradient(135deg,#1d4ed8,#2563eb);border-radius:16px 16px 0 0;padding:36px 40px;text-align:center;">
            <div style="font-size:32px;margin-bottom:8px;">🔑</div>
            <h1 style="margin:0;color:#fff;font-size:22px;font-weight:700;">Warehouse Manager</h1>
            <p style="margin:8px 0 0;color:#93c5fd;font-size:14px;">Password reset request</p>
          </td>
        </tr>
        <tr>
          <td style="background:#fff;padding:36px 40px;text-align:center;">
            <p style="margin:0 0 8px;font-size:16px;color:#1e293b;">Hi <strong>${name}</strong>,</p>
            <p style="margin:0 0 28px;font-size:14px;color:#64748b;line-height:1.6;">
              We received a request to reset your password. Click the button below.
              This link expires in <strong>1 hour</strong>. If you didn't request this, ignore this email.
            </p>
            <a href="${link}" style="display:inline-block;background:linear-gradient(135deg,#2563eb,#7c3aed);color:#fff;font-size:15px;font-weight:600;text-decoration:none;padding:14px 36px;border-radius:12px;">
              Reset Password
            </a>
            <p style="margin:24px 0 0;font-size:12px;color:#94a3b8;">
              Or copy this link:<br>
              <span style="color:#2563eb;word-break:break-all;">${link}</span>
            </p>
          </td>
        </tr>
        <tr>
          <td style="background:#1e293b;border-radius:0 0 16px 16px;padding:20px 40px;text-align:center;">
            <p style="margin:0;font-size:12px;color:#64748b;">
              Generated by <strong style="color:#93c5fd;">Warehouse Manager</strong> · Powered by PixelCore
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`,
  };
}
