function esc(s: string): string {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

const BREVO_API_KEY    = process.env.BREVO_API_KEY!;
const SENDER_EMAIL     = process.env.BREVO_SENDER_EMAIL!;
const SENDER_NAME      = process.env.BREVO_SENDER_NAME!;
const APP_URL          = process.env.NEXT_PUBLIC_APP_URL!;

interface SendOptions {
  to: string;
  toName?: string;
  subject: string;
  html: string;
}

export async function sendEmail({ to, toName, subject, html }: SendOptions) {
  const res = await fetch('https://api.brevo.com/v3/smtp/email', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'api-key': BREVO_API_KEY,
    },
    body: JSON.stringify({
      sender: { name: SENDER_NAME, email: SENDER_EMAIL },
      to: [{ email: to, name: toName || to }],
      subject,
      htmlContent: html,
    }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error((err as any).message || `Brevo error ${res.status}`);
  }
}

export function verificationEmail(name: string, token: string) {
  const link = `${APP_URL}/auth/callback?token=${token}`;
  return {
    subject: 'Verify your email — Warehouse Manager',
    html: `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:40px 16px;">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="max-width:560px;width:100%;">
        <tr>
          <td style="background:linear-gradient(135deg,#1d4ed8,#2563eb);border-radius:16px 16px 0 0;padding:36px 40px;text-align:center;">
            <div style="display:inline-block;background:#0f0f0f;border-radius:12px;width:48px;height:48px;text-align:center;line-height:48px;margin-bottom:14px;"><span style="color:white;font-family:Arial Black,Arial,Helvetica,sans-serif;font-weight:900;font-size:20px;font-style:italic;letter-spacing:-2px;">WM</span></div>
            <h1 style="margin:0;color:#fff;font-size:22px;font-weight:700;">Warehouse Manager</h1>
            <p style="margin:8px 0 0;color:#93c5fd;font-size:14px;">Verify your email address</p>
          </td>
        </tr>
        <tr>
          <td style="background:#fff;padding:36px 40px;text-align:center;">
            <p style="margin:0 0 8px;font-size:16px;color:#1e293b;">Hi <strong>${esc(name)}</strong>,</p>
            <p style="margin:0 0 28px;font-size:14px;color:#64748b;line-height:1.6;">
              Click the button below to verify your email and activate your account.
              This link expires in <strong>24 hours</strong>.
            </p>
            <a href="${link}" style="display:inline-block;background:linear-gradient(135deg,#2563eb,#7c3aed);color:#fff;font-size:15px;font-weight:600;text-decoration:none;padding:14px 36px;border-radius:12px;">
              Verify Email
            </a>
            <p style="margin:24px 0 0;font-size:12px;color:#94a3b8;">
              Or copy this link:<br>
              <span style="color:#2563eb;word-break:break-all;">${link}</span>
            </p>
          </td>
        </tr>
        <tr>
          <td style="background:#1e293b;border-radius:0 0 16px 16px;padding:20px 40px;text-align:center;">
            <p style="margin:0;font-size:12px;color:#64748b;">
              Generated by <strong style="color:#93c5fd;">Warehouse Manager</strong> · Powered by PixelCore
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`,
  };
}

export function adminNewRequestEmail(companyName: string, ownerName: string, ownerEmail: string) {
  return {
    subject: `Nueva solicitud — ${companyName}`,
    html: `<!DOCTYPE html>
<html lang="es">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:40px 16px;">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="max-width:560px;width:100%;">
        <tr>
          <td style="background:linear-gradient(135deg,#1d4ed8,#2563eb);border-radius:16px 16px 0 0;padding:36px 40px;text-align:center;">
            <div style="display:inline-block;background:#0f0f0f;border-radius:12px;width:48px;height:48px;text-align:center;line-height:48px;margin-bottom:14px;"><span style="color:white;font-family:Arial Black,Arial,Helvetica,sans-serif;font-weight:900;font-size:20px;font-style:italic;letter-spacing:-2px;">WM</span></div>
            <h1 style="margin:0;color:#fff;font-size:22px;font-weight:700;">Warehouse Manager</h1>
            <p style="margin:8px 0 0;color:#93c5fd;font-size:14px;">Nueva solicitud de acceso</p>
          </td>
        </tr>
        <tr>
          <td style="background:#fff;padding:36px 40px;">
            <p style="margin:0 0 16px;font-size:16px;color:#1e293b;font-weight:600;">Nueva empresa solicitando acceso</p>
            <table width="100%" style="border-collapse:collapse;font-size:14px;color:#374151;">
              <tr><td style="padding:8px 0;border-bottom:1px solid #f1f5f9;color:#6b7280;width:120px;">Empresa</td><td style="padding:8px 0;border-bottom:1px solid #f1f5f9;font-weight:600;">${esc(companyName)}</td></tr>
              <tr><td style="padding:8px 0;border-bottom:1px solid #f1f5f9;color:#6b7280;">Dueño</td><td style="padding:8px 0;border-bottom:1px solid #f1f5f9;">${esc(ownerName)}</td></tr>
              <tr><td style="padding:8px 0;color:#6b7280;">Email</td><td style="padding:8px 0;">${esc(ownerEmail)}</td></tr>
            </table>
          </td>
        </tr>
        <tr>
          <td style="background:#1e293b;border-radius:0 0 16px 16px;padding:20px 40px;text-align:center;">
            <p style="margin:0;font-size:12px;color:#64748b;">
              Generado por <strong style="color:#93c5fd;">Warehouse Manager</strong> · Powered by PixelCore
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`,
  };
}

export function clientApprovedEmail(ownerName: string, companyName: string) {
  const loginUrl = `${APP_URL}/login`;
  return {
    subject: '¡Cuenta aprobada! — Warehouse Manager',
    html: `<!DOCTYPE html>
<html lang="es">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:40px 16px;">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="max-width:560px;width:100%;">
        <tr>
          <td style="background:linear-gradient(135deg,#059669,#10b981);border-radius:16px 16px 0 0;padding:36px 40px;text-align:center;">
            <div style="display:inline-block;background:#0f0f0f;border-radius:12px;width:48px;height:48px;text-align:center;line-height:48px;margin-bottom:14px;"><span style="color:white;font-family:Arial Black,Arial,Helvetica,sans-serif;font-weight:900;font-size:20px;font-style:italic;letter-spacing:-2px;">WM</span></div>
            <h1 style="margin:0;color:#fff;font-size:22px;font-weight:700;">Warehouse Manager</h1>
            <p style="margin:8px 0 0;color:#a7f3d0;font-size:14px;">Tu cuenta fue aprobada</p>
          </td>
        </tr>
        <tr>
          <td style="background:#fff;padding:36px 40px;text-align:center;">
            <p style="margin:0 0 8px;font-size:16px;color:#1e293b;">Hola <strong>${esc(ownerName)}</strong>,</p>
            <p style="margin:0 0 24px;font-size:14px;color:#64748b;line-height:1.6;">
              Tu empresa <strong>${esc(companyName)}</strong> ha sido aprobada.<br>
              Ya podés iniciar sesión y comenzar a usar Warehouse Manager.
            </p>
            <a href="${loginUrl}" style="display:inline-block;background:linear-gradient(135deg,#059669,#10b981);color:#fff;font-size:15px;font-weight:600;text-decoration:none;padding:14px 36px;border-radius:12px;">
              Iniciar sesión
            </a>
          </td>
        </tr>
        <tr>
          <td style="background:#1e293b;border-radius:0 0 16px 16px;padding:20px 40px;text-align:center;">
            <p style="margin:0;font-size:12px;color:#64748b;">
              Generado por <strong style="color:#93c5fd;">Warehouse Manager</strong> · Powered by PixelCore
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`,
  };
}

export function clientRejectedEmail(ownerName: string, companyName: string) {
  return {
    subject: 'Solicitud no aprobada — Warehouse Manager',
    html: `<!DOCTYPE html>
<html lang="es">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:40px 16px;">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="max-width:560px;width:100%;">
        <tr>
          <td style="background:linear-gradient(135deg,#dc2626,#ef4444);border-radius:16px 16px 0 0;padding:36px 40px;text-align:center;">
            <div style="display:inline-block;background:#0f0f0f;border-radius:12px;width:48px;height:48px;text-align:center;line-height:48px;margin-bottom:14px;"><span style="color:white;font-family:Arial Black,Arial,Helvetica,sans-serif;font-weight:900;font-size:20px;font-style:italic;letter-spacing:-2px;">WM</span></div>
            <h1 style="margin:0;color:#fff;font-size:22px;font-weight:700;">Warehouse Manager</h1>
            <p style="margin:8px 0 0;color:#fca5a5;font-size:14px;">Solicitud de acceso</p>
          </td>
        </tr>
        <tr>
          <td style="background:#fff;padding:36px 40px;text-align:center;">
            <p style="margin:0 0 8px;font-size:16px;color:#1e293b;">Hola <strong>${esc(ownerName)}</strong>,</p>
            <p style="margin:0 0 24px;font-size:14px;color:#64748b;line-height:1.6;">
              Lamentablemente tu solicitud para la empresa <strong>${esc(companyName)}</strong> no fue aprobada en este momento.<br>
              Si creés que es un error, respondé este email para que podamos revisarlo.
            </p>
          </td>
        </tr>
        <tr>
          <td style="background:#1e293b;border-radius:0 0 16px 16px;padding:20px 40px;text-align:center;">
            <p style="margin:0;font-size:12px;color:#64748b;">
              Generado por <strong style="color:#93c5fd;">Warehouse Manager</strong> · Powered by PixelCore
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`,
  };
}

export function clientDeletedEmail(ownerName: string, companyName: string) {
  return {
    subject: 'Cuenta eliminada — Warehouse Manager',
    html: `<!DOCTYPE html>
<html lang="es">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:40px 16px;">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="max-width:560px;width:100%;">
        <tr>
          <td style="background:linear-gradient(135deg,#374151,#1f2937);border-radius:16px 16px 0 0;padding:36px 40px;text-align:center;">
            <div style="display:inline-block;background:#0f0f0f;border-radius:12px;width:48px;height:48px;text-align:center;line-height:48px;margin-bottom:14px;"><span style="color:white;font-family:Arial Black,Arial,Helvetica,sans-serif;font-weight:900;font-size:20px;font-style:italic;letter-spacing:-2px;">WM</span></div>
            <h1 style="margin:0;color:#fff;font-size:22px;font-weight:700;">Warehouse Manager</h1>
            <p style="margin:8px 0 0;color:#9ca3af;font-size:14px;">Notificación de cuenta</p>
          </td>
        </tr>
        <tr>
          <td style="background:#fff;padding:36px 40px;text-align:center;">
            <p style="margin:0 0 8px;font-size:16px;color:#1e293b;">Hola <strong>${esc(ownerName)}</strong>,</p>
            <p style="margin:0 0 24px;font-size:14px;color:#64748b;line-height:1.6;">
              Tu empresa <strong>${esc(companyName)}</strong> y todos sus datos han sido eliminados de Warehouse Manager.<br>
              Si tenés preguntas, respondé este email.
            </p>
          </td>
        </tr>
        <tr>
          <td style="background:#1e293b;border-radius:0 0 16px 16px;padding:20px 40px;text-align:center;">
            <p style="margin:0;font-size:12px;color:#64748b;">Generado por <strong style="color:#93c5fd;">Warehouse Manager</strong> · Powered by PixelCore</p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`,
  };
}

export function activationEmail(ownerName: string, companyName: string, link: string) {
  return {
    subject: 'Tu acceso a Warehouse Manager está listo',
    html: `<!DOCTYPE html>
<html lang="es">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:40px 16px;">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="max-width:560px;width:100%;">
        <tr>
          <td style="background:linear-gradient(135deg,#059669,#10b981);border-radius:16px 16px 0 0;padding:36px 40px;text-align:center;">
            <div style="display:inline-block;background:#0f0f0f;border-radius:12px;width:48px;height:48px;text-align:center;line-height:48px;margin-bottom:14px;"><span style="color:white;font-family:Arial Black,Arial,Helvetica,sans-serif;font-weight:900;font-size:20px;font-style:italic;letter-spacing:-2px;">WM</span></div>
            <h1 style="margin:0;color:#fff;font-size:22px;font-weight:700;">Warehouse Manager</h1>
            <p style="margin:8px 0 0;color:#a7f3d0;font-size:14px;">Código de activación</p>
          </td>
        </tr>
        <tr>
          <td style="background:#fff;padding:36px 40px;text-align:center;">
            <p style="margin:0 0 8px;font-size:16px;color:#1e293b;">Hola <strong>${esc(ownerName)}</strong>,</p>
            <p style="margin:0 0 28px;font-size:14px;color:#64748b;line-height:1.6;">
              Tu empresa <strong>${esc(companyName)}</strong> ha sido revisada.<br>
              Hacé clic en el botón para activar tu cuenta. El enlace expira en <strong>1 hora</strong>.
            </p>
            <a href="${link}" style="display:inline-block;background:linear-gradient(135deg,#059669,#10b981);color:#fff;font-size:15px;font-weight:600;text-decoration:none;padding:14px 36px;border-radius:12px;">
              Activar mi cuenta
            </a>
            <p style="margin:24px 0 0;font-size:12px;color:#94a3b8;">
              O copiá este enlace:<br>
              <span style="color:#059669;word-break:break-all;">${link}</span>
            </p>
          </td>
        </tr>
        <tr>
          <td style="background:#1e293b;border-radius:0 0 16px 16px;padding:20px 40px;text-align:center;">
            <p style="margin:0;font-size:12px;color:#64748b;">
              Generado por <strong style="color:#93c5fd;">Warehouse Manager</strong> · Powered by PixelCore
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`,
  };
}

export function snapshotReportEmail(opts: {
  warehouseName: string;
  date: string;
  total: number;
  pending: number;
  ready: number;
  delivered: number;
  vaults: { row: string; column: number; level: number; client_name: string; estado?: string; status?: string }[];
}) {
  const { warehouseName, date, total, pending, ready, delivered, vaults } = opts;
  const rows = ['A','B','C','D','E','F','G','H','I','J'];
  const cols = [1,2,3,4,5,6,7,8];

  const statusColor = (s: string) =>
    s === 'READY' ? '#dcfce7' : s === 'DELIVERED' ? '#dbeafe' : s === 'PENDING' ? '#fef9c3' : '#f1f5f9';
  const statusText = (s: string) =>
    s === 'READY' ? '#15803d' : s === 'DELIVERED' ? '#1d4ed8' : s === 'PENDING' ? '#a16207' : '#6b7280';

  const buildGrid = (level: number) => {
    const label = level === 1 ? 'LOWER LEVEL' : 'UPPER LEVEL';
    let rows_html = '';
    rows.forEach(row => {
      let cells = '';
      cols.forEach(col => {
        const v = vaults.find(b => b.row === row && Number(b.column) === col && Number(b.level) === level);
        const st = v ? (v.estado || v.status || 'PENDING') : '';
        cells += v
          ? `<td style="padding:4px 3px;text-align:center;background:${statusColor(st)};border:1px solid #e2e8f0;border-radius:4px;">
               <div style="font-size:9px;font-weight:700;color:${statusText(st)};line-height:1.2;">${esc(v.client_name).slice(0,8)}</div>
               <div style="font-size:8px;color:${statusText(st)};opacity:.8;">${esc(st).slice(0,3)}</div>
             </td>`
          : `<td style="padding:4px 3px;text-align:center;background:#f8fafc;border:1px solid #e2e8f0;border-radius:4px;"><span style="color:#cbd5e1;font-size:10px;">-</span></td>`;
      });
      rows_html += `<tr><td style="padding:4px 6px;font-size:11px;font-weight:700;color:#475569;text-align:center;">${row}</td>${cells}</tr>`;
    });

    const header = cols.map(c => `<td style="padding:4px 3px;text-align:center;font-size:10px;font-weight:600;color:#94a3b8;">C${c}</td>`).join('');

    return `
      <div style="margin-bottom:24px;">
        <div style="font-size:11px;font-weight:700;color:#64748b;letter-spacing:1px;text-transform:uppercase;margin-bottom:8px;">${label}</div>
        <table cellpadding="0" cellspacing="3" style="border-collapse:separate;width:100%;">
          <thead><tr><td style="width:20px;"></td>${header}</tr></thead>
          <tbody>${rows_html}</tbody>
        </table>
      </div>`;
  };

  return {
    subject: `Snapshot Report — ${esc(warehouseName)} · ${esc(date)}`,
    html: `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:40px 16px;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;">

        <!-- Header -->
        <tr>
          <td style="background:linear-gradient(135deg,#1d4ed8,#2563eb);border-radius:16px 16px 0 0;padding:32px 40px;text-align:center;">
            <div style="display:inline-block;background:#0f0f0f;border-radius:12px;width:48px;height:48px;text-align:center;line-height:48px;margin-bottom:12px;">
              <span style="color:white;font-family:Arial Black,Arial,Helvetica,sans-serif;font-weight:900;font-size:20px;font-style:italic;letter-spacing:-2px;">WM</span>
            </div>
            <h1 style="margin:0;color:#fff;font-size:20px;font-weight:700;">Warehouse Manager</h1>
            <p style="margin:6px 0 0;color:#93c5fd;font-size:13px;">Snapshot Report</p>
          </td>
        </tr>

        <!-- Warehouse + Date -->
        <tr>
          <td style="background:#1e40af;padding:14px 40px;text-align:center;">
            <span style="color:#bfdbfe;font-size:14px;font-weight:600;">${esc(warehouseName)}</span>
            <span style="color:#60a5fa;margin:0 10px;">·</span>
            <span style="color:#bfdbfe;font-size:14px;">${esc(date)}</span>
          </td>
        </tr>

        <!-- Stats -->
        <tr>
          <td style="background:#fff;padding:28px 40px 20px;">
            <table width="100%" cellpadding="0" cellspacing="0">
              <tr>
                <td style="width:25%;padding:0 6px 0 0;">
                  <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:16px;text-align:center;">
                    <div style="font-size:28px;font-weight:800;color:#0f172a;line-height:1;">${total}</div>
                    <div style="font-size:11px;color:#64748b;margin-top:4px;font-weight:500;">Total Vaults</div>
                  </div>
                </td>
                <td style="width:25%;padding:0 3px;">
                  <div style="background:#fefce8;border:1px solid #fef08a;border-radius:12px;padding:16px;text-align:center;">
                    <div style="font-size:28px;font-weight:800;color:#854d0e;line-height:1;">${pending}</div>
                    <div style="font-size:11px;color:#a16207;margin-top:4px;font-weight:500;">Pending</div>
                  </div>
                </td>
                <td style="width:25%;padding:0 3px;">
                  <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:12px;padding:16px;text-align:center;">
                    <div style="font-size:28px;font-weight:800;color:#14532d;line-height:1;">${ready}</div>
                    <div style="font-size:11px;color:#15803d;margin-top:4px;font-weight:500;">Ready</div>
                  </div>
                </td>
                <td style="width:25%;padding:0 0 0 3px;">
                  <div style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:12px;padding:16px;text-align:center;">
                    <div style="font-size:28px;font-weight:800;color:#1e3a8a;line-height:1;">${delivered}</div>
                    <div style="font-size:11px;color:#1d4ed8;margin-top:4px;font-weight:500;">Delivered</div>
                  </div>
                </td>
              </tr>
            </table>
          </td>
        </tr>

        <!-- Grid -->
        <tr>
          <td style="background:#fff;padding:8px 40px 28px;">
            <div style="font-size:12px;font-weight:700;color:#374151;letter-spacing:.5px;margin-bottom:16px;padding-bottom:10px;border-bottom:1px solid #f1f5f9;">WAREHOUSE GRID</div>
            ${buildGrid(1)}
            ${buildGrid(2)}
            <!-- Legend -->
            <table cellpadding="0" cellspacing="0" style="margin-top:8px;">
              <tr>
                <td style="padding-right:12px;"><span style="display:inline-block;width:10px;height:10px;background:#fef9c3;border-radius:2px;margin-right:4px;"></span><span style="font-size:11px;color:#64748b;">Pending</span></td>
                <td style="padding-right:12px;"><span style="display:inline-block;width:10px;height:10px;background:#dcfce7;border-radius:2px;margin-right:4px;"></span><span style="font-size:11px;color:#64748b;">Ready</span></td>
                <td style="padding-right:12px;"><span style="display:inline-block;width:10px;height:10px;background:#dbeafe;border-radius:2px;margin-right:4px;"></span><span style="font-size:11px;color:#64748b;">Delivered</span></td>
              </tr>
            </table>
          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="background:#1e293b;border-radius:0 0 16px 16px;padding:20px 40px;text-align:center;">
            <p style="margin:0;font-size:12px;color:#64748b;">
              Generated by <strong style="color:#93c5fd;">Warehouse Manager</strong> · Powered by PixelCore
            </p>
          </td>
        </tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`,
  };
}

export function passwordResetEmail(name: string, token: string) {
  const link = `${APP_URL}/reset-password?token=${token}`;
  return {
    subject: 'Reset your password — Warehouse Manager',
    html: `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:40px 16px;">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="max-width:560px;width:100%;">
        <tr>
          <td style="background:linear-gradient(135deg,#1d4ed8,#2563eb);border-radius:16px 16px 0 0;padding:36px 40px;text-align:center;">
            <div style="display:inline-block;background:#0f0f0f;border-radius:12px;width:48px;height:48px;text-align:center;line-height:48px;margin-bottom:14px;"><span style="color:white;font-family:Arial Black,Arial,Helvetica,sans-serif;font-weight:900;font-size:20px;font-style:italic;letter-spacing:-2px;">WM</span></div>
            <h1 style="margin:0;color:#fff;font-size:22px;font-weight:700;">Warehouse Manager</h1>
            <p style="margin:8px 0 0;color:#93c5fd;font-size:14px;">Password reset request</p>
          </td>
        </tr>
        <tr>
          <td style="background:#fff;padding:36px 40px;text-align:center;">
            <p style="margin:0 0 8px;font-size:16px;color:#1e293b;">Hi <strong>${esc(name)}</strong>,</p>
            <p style="margin:0 0 28px;font-size:14px;color:#64748b;line-height:1.6;">
              We received a request to reset your password. Click the button below.
              This link expires in <strong>1 hour</strong>. If you didn't request this, ignore this email.
            </p>
            <a href="${link}" style="display:inline-block;background:linear-gradient(135deg,#2563eb,#7c3aed);color:#fff;font-size:15px;font-weight:600;text-decoration:none;padding:14px 36px;border-radius:12px;">
              Reset Password
            </a>
            <p style="margin:24px 0 0;font-size:12px;color:#94a3b8;">
              Or copy this link:<br>
              <span style="color:#2563eb;word-break:break-all;">${link}</span>
            </p>
          </td>
        </tr>
        <tr>
          <td style="background:#1e293b;border-radius:0 0 16px 16px;padding:20px 40px;text-align:center;">
            <p style="margin:0;font-size:12px;color:#64748b;">
              Generated by <strong style="color:#93c5fd;">Warehouse Manager</strong> · Powered by PixelCore
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`,
  };
}
